// Package internal provides a way to obtain information about which database
// drivers were included at build.
package internal

// Code generated by gen.go. DO NOT EDIT.

// KnownBuildTags returns a map of known driver names to its respective build
// tags.
func KnownBuildTags() map[string]string {
	return map[string]string{
		"cassandra": "cql",       // github.com/MichaelS11/go-cql-driver
		"cosmos":    "cosmos",    // github.com/btnguyen2k/gocosmos
		"csvq":      "csvq",      // github.com/mithrandie/csvq-driver
		"mymysql":   "mymysql",   // github.com/ziutek/mymysql/godrv
		"mysql":     "mysql",     // github.com/go-sql-driver/mysql
		"odbc":      "odbc",      // github.com/alexbrainman/odbc
		"oracle":    "oracle",    // github.com/sijms/go-ora/v2
		"postgres":  "postgres",  // github.com/lib/pq
		"ql":        "ql",        // modernc.org/ql
		"snowflake": "snowflake", // github.com/snowflakedb/gosnowflake
		"sqlite3":   "sqlite3",   // github.com/mattn/go-sqlite3
		"sqlserver": "sqlserver", // github.com/microsoft/go-mssqldb
	}
}
